### ISSUE TITLE
ChromePac无锡有线通用户没有办法使用

### ISSUE THREAD

**Issue by hijklmn** [comeforu2012/truth#9]
前几天还很快，使用正常，从昨天起gmail没有办法打开，google网站基本上都不行了。

**Comment by comeforu2012** [comment]
有几个服务器被封了

2015-10-07 10:20 GMT+08:00 hijklmn <notifications@github.com>:

**Comment by hijklmn** [comment]
@comeforu2012 期待你们尽快更新，让它能够重新工作。
